var GAME_LEVELS = [
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                  ###                         ",
   "                                                                                 #####                        ",
   "        ###                                                                       ###                         ",
   "       #####                                                  ###                                             ",
   "        ###                                                  #####                                            ",
   "                          ###                                 ###                                             ",
   "                         #####                                                                                ",
   "                          ###                                                                                 ",
   "                                                                                                              ",
   "                                                                         o            o         o             ",
   "                                                                          a                               o?? ",
   "                                                                      xxxxxxxxx      xxxx     xxxx      xxcccc",
   "              o       o       o              o               o       xzzzzzzzzz                           zccc",
   "? @                       a                                    a    xzzzzzzzzzz                            zcc",
   "ccccxxxxxxxxxxx   x   xxxxxxxxx     xxx     xxx     xxx    xxxxxxxxxzzzzzzzzzzz                             zc",
   "cccczzzzzzzzzzz!!!z!!!zzzzzzzzz                            zzzzzzzzzzzzzzzzzzzz                              z",
   "cccczzzzzzzzzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!zzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!z",
   "cccczzzzzzzzzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!zzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!z",
   "cccczzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"],

   ["c     xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                        xxxxxxxxxxxxxxxxxx",
    "z  @  zzzzzzzzzzzzzzzzzzzzzzzzzzzzz                                                        zzzzzzzzzzzzzzzzzz",
    "z                 zzzzzzzzzzzzzzzzz                                                        zzzzzzzzzzzzzzzzzz",
    "z                  zzzzzzzzzzzzzzzz                                                        zzzzzzzzzzzzzzzzzz",
    "z                   zzzzzzzzzzzzzzz                                                        zzzzzzzzzzzzzzzzzz",
    "z         o          zzzzzz!!!zzzzz                       o            o                   zzzzzzzzzzzzzzzzzz",
    "z?                    zzzz!!!!!zzzz                          a      a                      zzzzzzzzzzzzzzzzzz",
    "zxxxxx!!!xxx!!!!xx    zzzzz!!!zzzzz                    xxxxxxxxxxxxxxxxxxxx                zzzzzzzzzzzzzzzzzz",
    "zzzzzzzzzzzzzzzzzz    zzzzzzvzzzzzz             x      z!!!!!!!!!!!!!!!!!!z        a       zzzzzzzzzzzzzzzzzz",
    "z                     zzz       zzz                    z!!vvvv!!vvvvv!!vvvz                zzzzzzzzzzzzzzzzzz",
    "z                     zz  z   z  zz        o                                       a       zzzzzzzzzzzzzzzzzz",
    "z                     zz         zz        x                                               zzzzzzzzzzzzzzzzzz",
    "z           a         zz         zz                                                a       zzzzzzzzzzzzzzzzzz",
    "z   xxxxxxxxxxxxxxxxxxzz  z   z  zz                                                        zzzzzzzzzzzzzzzzzz",
    "z   zzzzzzzzzzzzzzzzzzzz   zoz   zz             x                                          zzzzzzzzzzzzzzzzzz",
    "z                     zzz       zzz                           oo            o               o                ",
    "z                     zzzz     zzzz        o                                                                 ",
    "z o          o                             x            xx    xx     xx    xxx      x      xxx          o    ",
    "z o          a                                                                                            ???",
    "zxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx",
    "zzzzzzzzzzzzzzzzzzzzzzzzzzz!!!zzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!zzzzzzz"],

    ["zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzzz                                                                                                      ",
     "zzzzzz                                                                                                       ",
     "zzzzz                                                                                                        ",
     "                                                                                                             ",
     "                                                 b                                                           ",
     "  @                                                                                                          ",
     "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz            zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"],

     ["                                                                          ",
      "                                                                          ",
      "                                                                          ",
      "                                                                          ",
      "                                                                          ",
      "                                                                          ",
      "                       o   o ooo o o   o     o ooo oo  o  o               ",
      "                        o o  o o o o   o  o  o  o  o o o  o               ",
      "                         o   o o o o   o o o o  o  o o o  o               ",
      "                         o   o o o o   oo   oo  o  o o o                  ",
      "                         o   ooo ooo   o     o ooo o  oo  o               ",
      "                                                                          ",
      "  @                                                                       ",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
